[[team]]
enable = true
name   = "Iglou.eu"
error  = ["mail", "rest-tchat"]

    [[team.app]]
    name     = "iglou web site"
    url      = "https://iglou.eu/"
    response = 200

    [[team.app]]
    name     = "iglou false site"
    url      = "https://vps685796.ovh.net:2087"
    response = 2000

[[team]]
enable = false
name   = "test"
