[overall]
loopWait = 10 # Second before retry evry thing
logFile = './result.log'
logVerbose = false
checkListFile = './examples/etc/xavier-srv/check.toml'
errorListFile = './examples/etc/xavier-srv/errors.toml'

[http]
maxWait = 120 # Max Microsecond between each request

[reporting]
local = true
dir   = './examples/var/www/'