[team.IglouEu]
    [[team.IglouEu.report]]
    process    = 'smtp'
    host       = 'mail.gandi.net:465'
    from       = 'Professeur Xavier <pxavier@iglou.eu>'
    user       = ''
    passwd     = ''
    recipients = ['a@a.a', 'b@b.b']
    subject    = '🤯 [WRNING][[%TEAM]] Error on webapp'
    body       = '''
        Some WebAPP from '[%TEAM]' have failed.
        [%ERRORS]
        '''

    [[team.IglouEu.report]]
    process = 'http'
    methods = 'POST'
    url     = 'https://toto.tata/hooks/xxxxxxxxxxxxxxxxxxxxxx'
    body    = '{"team": "[%TEAM]", "errors": "[%ERRORS]"}'
